# Generated by Django 5.1.6 on 2025-02-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio_lanzamiento', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artista')),
            ],
        ),
    ]
