# Generated by Django 5.1.6 on 2025-02-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='pais_origen',
        ),
        migrations.AddField(
            model_name='artista',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible'),
        ),
    ]
